### ISSUE TITLE
Filename error

### ISSUE THREAD

**Issue by asubiotto** [bonsaistudio/django-image-tools#4]
Hi, I believe that on [line 376 of models.py](https://github.com/bonsaistudio/django-image-tools/blob/master/django_image_tools/models.py#L376) imageObject.filename should be filename otherwise calling path_for_image(image) with image.image.name = "hello.png" returns "hello.png.png"

**Comment by xelhark** [comment]
Thanks for the pull request!

**Comment by asubiotto** [comment]
You're welcome, but it wasn't a complete pull request. I think that some tests need to be changed.
